["groups.misc"]
repos = [
    "ayuspoudel",
    "Resume",
]

["groups.terraform"]
repos = [
    "Terraform-best-methods",
    "terraform-github-ayuspo",
    "Terraform-Automation-Projects",
]

["groups.dynatrace"]
repos = [
    "dynatrace-terraform-observability-dashboards",
]

["groups.legacy"]
repos = [
    "legacy-cpp-library-adt-dsa",
    "legacy-cpp-polish-reverse-polish-converter",
    "legacy-cpp-sorting-techniques",
    "legacy-java-learning-problems",
    "legacy-c-language-projects",
]

["groups.ansible"]
repos = [
    "ansible-windows-bootstrap",
    "ansible-playbooks-common-devops",
]

["groups.developed-applications"]
repos = [
    "dotmanz",
    "homebrew-dotmanz",
]

["groups.ops"]
repos = [
    "observability-zero-to-hero",
    "vm-health-check",
    "Shell-Scripting-Projects",
    "CICD-Pipeline-Implementation-Jenkins-ArgoCD-Kubernetes",
    "kubernetes-demo-app",
    "Python",
]

["groups.aws"]
repos = [
    "aws-service-notes",
    "aws-cli-automation-scripts",
    "aws-3tier-web-architecture",
    "aws-cloud-native-microservices-deployment",
    "aws-lambda-serverless-jira-github-sync",
    "aws-iac-terraform-monorepo",
    "aws-mongodb-ha-replicaset-cluster",
]

["groups.web-development"]
repos = [
    "webdev-clone-amazon",
    "webdev-tool-microservices-blog",
    "webdev-ui-dropdown-menu",
    "webdev-app-flat-guru-usf",
    "webdev-app-green-rise-nepal",
    "webdev-learn-js-journey",
    "webdev-portfolio-main",
    "webdev-learn-js-projects",
    "webdev-app-weather",
]
