["groups.repo-ansible"]
repos = [
    "ansible-windows-bootstrap",
    "ansible-playbooks-common-devops",
]

["groups.repo-legacy"]
repos = [
    "legacy-cpp-library-adt-dsa",
    "legacy-cpp-polish-reverse-polish-converter",
    "legacy-cpp-sorting-techniques",
    "legacy-java-learning-problems",
    "legacy-c-language-projects",
]

["groups.repo-web-development"]
repos = [
    "webdev-clone-amazon",
    "webdev-tool-microservices-blog",
    "webdev-ui-dropdown-menu",
    "webdev-app-flat-guru-usf",
    "webdev-app-green-rise-nepal",
    "webdev-learn-js-journey",
    "webdev-portfolio-main",
    "webdev-learn-js-projects",
    "webdev-app-weather",
]

["groups.repo-developed-applications"]
repos = [
    "dmz",
    "homebrew-dmz",
]

["groups.repo-aws"]
repos = [
    "aws-service-notes",
    "aws-cli-automation-scripts",
    "aws-3tier-web-architecture",
    "aws-cloud-native-microservices-deployment",
    "aws-lambda-serverless-jira-github-sync",
    "aws-iac-terraform-monorepo",
    "aws-mongodb-ha-replicaset-cluster",
]

["groups.repo-dynatrace"]
repos = [
    "dynatrace-terraform-observability-dashboards",
]

["groups.repo-terraform"]
repos = [
    "Terraform-best-methods",
    "terraform-github-ayuspo",
    "Terraform-Automation-Projects",
]

["groups.repo-misc"]
repos = [
    "ayuspoudel-resume",
    "ayuspoudel",
]

["groups.repo-ops"]
repos = [
    "ops-shell-scripting-automation",
    "ops-cicd-pipeline-jenkins-argocd-k8s",
    "ops-kubernetes-demo-application",
    "ops-python-infra-utilities",
]
