[package]
name = "github-token-gen"
version = "0.1.0"
edition = "2024"

[dependencies]
toml = "0.8"
serde = { version = "1", features = ["derive"] }
chrono = "0.4"
jsonwebtoken = "9"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }


