# .github/workflows/create-secrets.yml
name: Create GitHub Repo Secrets

on:
  workflow_dispatch:
    inputs:
      target_directory:
        description: "Select the folder to apply secrets to"
        required: true
        type: choice
        options:
        - repo-ansible
        - repo-aws
        - repo-developed-applications
        - repo-dynatrace
        - repo-legacy
        - repo-misc
        - repo-ops
        - repo-terraform
        - repo-web-development
      secrets_yaml:
        description: "YAML-formatted secrets with repo name as key"
        required: true
        type: string


jobs:
  apply-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Write secrets.yaml
      run: |
        echo "${{ github.event.inputs.secrets_yaml }}" > developed-applications/secrets.yaml

    - name: Run Terragrunt to apply secrets
      run: |
        cd developed-applications
        terragrunt apply -auto-approve

    - name: Clean up secrets file
      run: rm -f developed-applications/secrets.yaml
