name: Release terraform-provider-ghapptoken

on:
  push:
    tags:
      - 'terraform-provider-ghapptoken/v*'  # Only triggers on tags like ghapptoken/v0.1.0
permissions:
  contents: write

jobs:
  release:
    name: Build and Release Provider
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build binary
        run: |
          cd terraform-provider-ghapptoken
          mkdir -p ../dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -o ../dist/terraform-provider-ghapptoken_${{ matrix.goos }}_${{ matrix.goarch }}

      - name: Upload release artifact
        uses: softprops/action-gh-release@v1
        with:
          name: terraform-provider-ghapptoken
          files: dist/terraform-provider-ghapptoken_*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
