name: Release terraform-provider-ghapptoken

on:
  push:
    tags:
      - 'terraform-provider-ghapptoken/v*'  # e.g. terraform-provider-ghapptoken/v0.1.0

permissions:
  contents: write

jobs:
  release:
    name: Build and Release Provider
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Extract version
        id: version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/terraform-provider-ghapptoken/v}" >> $GITHUB_OUTPUT

      - name: Build and Zip
        run: |
          mkdir -p dist
          cd terraform-provider-ghapptoken
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ../dist/terraform-provider-ghapptoken_v${{ steps.version.outputs.VERSION }}_${{ matrix.goos }}_${{ matrix.goarch }}
          cd ../dist
          zip terraform-provider-ghapptoken_v${{ steps.version.outputs.VERSION }}_${{ matrix.goos }}_${{ matrix.goarch }}.zip terraform-provider-ghapptoken_v${{ steps.version.outputs.VERSION }}_${{ matrix.goos }}_${{ matrix.goarch }}

      - name: Generate SHA256SUMS
        run: |
          cd dist
          shasum -a 256 terraform-provider-ghapptoken_v${{ steps.version.outputs.VERSION }}_* > terraform-provider-ghapptoken_v${{ steps.version.outputs.VERSION }}_SHA256SUMS

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          name: terraform-provider-ghapptoken v${{ steps.version.outputs.VERSION }}
          files: |
            dist/terraform-provider-ghapptoken_v${{ steps.version.outputs.VERSION }}_*.zip
            dist/terraform-provider-ghapptoken_v${{ steps.version.outputs.VERSION }}_SHA256SUMS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
